In [1]:
import pandas as pd

#load the file
df=pd.read_excel('pandas_200_Employees.xlsx')

In [2]:
#problem 1:Identify and count the numbr of missing values in each column of the dataset

missing_value_count=df.isnull().sum()
print(missing_value_count)

EmployeeID      0
EmployeeName    0
Position        0
Age             0
Salary          0
Gender          0
Department      0
HireDate        0
dtype: int64

In [4]:
#problem 2: find and remove the duplicate records from the dataset

df_cleaned=df.drop_duplicates()
print("original Rows:",len(df))
print("Rows after removing duplicate:",len(df_cleaned))

original Rows: 200
Rows after removing duplicate: 200

In [8]:
#problem3:normalize the 'Age' columns using the min-max normalization technique.
#X_normalozed=(x-x_min)/(x_max-X_min)
min_age=df['Age'].min()
max_age=df['Age'].max()

df['Normalized_Age']=(df['Age']-min_age)/(max_age-min_age)
print(df[['Age','Normalized_Age']])

     Age  Normalized_Age
0     40        0.782609
1     44        0.956522
2     30        0.347826
3     33        0.478261
4     22        0.000000
..   ...             ...
195   25        0.130435
196   42        0.869565
197   27        0.217391
198   25        0.130435
199   22        0.000000

[200 rows x 2 columns]

In [10]:
#problem4:Standardised the 'Salary' column using the standardization technique.
#X_standarized=(x_mean)/standard deviation

mean_salary=df['Salary'].mean()
std_salary=df['Salary'].std()
df['Standardized_Salary']=(df['Salary']-mean_salary)/std_salary
print(df[['Salary','Standardized_Salary']])

     Salary  Standardized_Salary
0     55132            -0.531821
1     83223             0.912052
2     70536             0.259942
3     55224            -0.527093
4     65553             0.003816
..      ...                  ...
195   43915            -1.108374
196   56538            -0.459553
197   35714            -1.529904
198   82504             0.875095
199   57021            -0.434727

[200 rows x 2 columns]

In [12]:
#problem5:Fill in missing values in the 'Gender' column with the mode value.
mode_gender=df['Gender'].mode()[0]
df['Gender'].fillna(mode_gender,inplace=True)
print(df['Gender'])

0      Female
1      Female
2        Male
3        Male
4        Male
        ...
195      Male
196    Female
197      Male
198      Male
199    Female
Name: Gender, Length: 200, dtype: object

C:\Users\KIIT\AppData\Local\Temp\ipykernel_32060\2748934551.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(mode_gender,inplace=True)

In [13]:
#problem6: average salary by department
avg_salary_dept=df.groupby("Department")['Salary'].mean()
print(avg_salary_dept)

Department
Design        63871.740741
Finance       70609.322581
HR            63911.410256
IT            68421.057143
Management    68797.645161
Marketing     58440.945946
Name: Salary, dtype: float64

In [14]:
#problem7: Highest paid top 10 employees

top_10_employee=df.sort_values(by="Salary", ascending=False).head(10)
print(top_10_employee)

    EmployeeID   EmployeeName         Position  Age  Salary  Gender  \
132       E133  Deepak Sharma   Content Writer   28   99819  Female
88        E089   Suresh Gupta          Manager   29   99722    Male
67        E068    Arjun Yadav     Data Analyst   39   99242  Female
9         E010   Suresh Mehta     System Admin   37   98518    Male
87        E088  Shreya Sharma  DevOps Engineer   32   98187  Female
114       E115   Sunita Verma         Designer   27   97523    Male
151       E152  Deepak Sharma     Data Analyst   42   96757  Female
144       E145      Arjun Das     HR Executive   30   96492  Female
55        E056   Kavita Verma     HR Executive   41   95682  Female
52        E053   Deepak Singh      QA Engineer   42   95496  Female

     Department   HireDate  Normalized_Age  Standardized_Salary
132  Management 2017-05-24        0.260870             1.765084
88           HR 2018-04-16        0.304348             1.760098
67   Management 2019-12-10        0.739130             1.735426
9            IT 2017-01-01        0.652174             1.698213
87           IT 2023-09-01        0.434783             1.681199
114          IT 2022-10-15        0.217391             1.647070
151          HR 2023-04-03        0.869565             1.607698
144     Finance 2017-04-26        0.347826             1.594077
55      Finance 2019-12-16        0.826087             1.552443
52      Finance 2023-01-08        0.869565             1.542882

In [15]:
#problem8: Employee hired after 2020
df['HireDate']=pd.to_datetime(df['HireDate'])

employee_after_2020=df[df['HireDate'].dt.year>2020]
employee_after_2020.head()

,EmployeeID,EmployeeName,Position,Age,Salary,Gender,Department,HireDate,Normalized_Age,Standardized_Salary
0,E001,Sunita Singh,Designer,40,55132,Female,Marketing,2023-07-29,0.782609,-0.531821
6,E007,Arjun Rao,Manager,38,62092,Female,Marketing,2023-07-17,0.695652,-0.174078
15,E016,Karan Patel,Manager,45,92291,Male,Finance,2023-08-10,1.000000,1.378146
16,E017,Ayesha Das,HR Executive,44,60834,Male,HR,2023-04-26,0.956522,-0.238739
17,E018,Rohan Rao,HR Executive,33,83975,Female,IT,2022-11-26,0.478261,0.950705

In [16]:
#Gender-Wise Salary Comparison

gender_salary=df.groupby('Gender')['Salary'].mean()
gender_salary
df.groupby('Gender')['Salary'].agg(['min','max','mean'])

          min    max          mean
Gender
Female  30582  99819  65275.909091
Male    30422  99722  65677.574257

In [17]:
#Department with Youngest Average Age

avg_age_dept=df.groupby("Department")['Age'].mean()

youngest_dept= avg_age_dept.idxmin()
youngest_dept,avg_age_dept.min()

('IT', 31.82857142857143)